### Health
GET localhost:3000/api/health

### Version
GET localhost:3000/api/version

### Application Error
GET localhost:3000/api/application-error

### Generic Error
GET localhost:3000/api/generic-error
