apis:
  default:
    root: openapi.yaml
    x-openapi-ts:
      output: ./generated/openapi.ts
rules:
  security-defined: off
  info-license: off
  no-server-example.com: off
  operation-4xx-response: warn
